"""
MT5 Terminal Controller for automated backtesting.
Handles launching MT5, running backtests, and monitoring completion.
"""

import os
import subprocess
import time
import shutil
from datetime import datetime
from pathlib import Path
from typing import Optional, Dict, Any
import xml.etree.ElementTree as ET

from config import get_config, MT5Config, BacktestConfig


class MT5Controller:
    """
    Controls MT5 terminal for automated backtesting.

    Workflow:
    1. Generate config.ini for the test
    2. Copy .set file to appropriate location
    3. Launch MT5 with config
    4. Wait for completion (process exit or results file)
    5. Return path to results
    """

    # Timeframe mapping for config.ini
    TIMEFRAMES = {
        "M1": 1,
        "M5": 5,
        "M15": 15,
        "M30": 30,
        "H1": 60,
        "H4": 240,
        "D1": 1440,
        "W1": 10080,
        "MN1": 43200,
    }

    def __init__(self, mt5_config: Optional[MT5Config] = None):
        """
        Initialize the controller.

        Args:
            mt5_config: MT5 configuration. Loads from env if not provided.
        """
        if mt5_config is None:
            config = get_config()
            mt5_config = config.mt5

        self.config = mt5_config
        self.config.validate()

        # Create tester directory if needed
        self.tester_dir = Path(self.config.tester_path)
        self.tester_dir.mkdir(parents=True, exist_ok=True)

        # Results directory
        self.results_dir = self.tester_dir / "Results"
        self.results_dir.mkdir(parents=True, exist_ok=True)

    def _create_config_ini(
        self,
        set_file_path: str,
        backtest_config: BacktestConfig,
        output_path: Optional[str] = None
    ) -> str:
        """
        Create a config.ini file for MT5 tester.

        Args:
            set_file_path: Path to the .set file with EA parameters
            backtest_config: Backtest settings
            output_path: Where to save config.ini (default: tester folder)

        Returns:
            Path to the config.ini file
        """
        if output_path is None:
            # Write to Tester folder (where MT5 Strategy Tester reads from)
            output_path = str(self.tester_dir / "config.ini")

        # Get EA path relative to experts folder
        ea_name = self.config.ea_name

        # Convert timeframe
        tf_value = self.TIMEFRAMES.get(backtest_config.timeframe, 1)

        # Build config content - format must match MT5's expected format
        # Symbol needs .cash suffix for index CFDs
        symbol = backtest_config.symbol
        if not symbol.endswith('.cash') and symbol in ['US30', 'NAS100', 'US500']:
            symbol = f"{symbol}.cash"

        # Generate unique report name
        report_name = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

        config_content = f"""; MT5 Tester Configuration
; Generated by JJC Optimizer on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
[Tester]
Expert={ea_name}
Symbol={symbol}
Period={backtest_config.timeframe}
Optimization=0
Model={backtest_config.modeling_mode}
FromDate={backtest_config.start_date}
ToDate={backtest_config.end_date}
ForwardMode=0
Deposit={int(backtest_config.initial_deposit)}
Currency=USD
ProfitInPips=0
Leverage=100
ExecutionMode=0
OptimizationCriterion=0
Visual=0
ShutdownTerminal=1
Report={report_name}
ReplaceReport=1
[TesterInputs]
; Inputs loaded from .set file: {set_file_path}
"""

        # Store report name for later retrieval
        self._last_report_name = report_name

        # Use ASCII encoding (MT5 Tester expects plain text, NOT UTF-16)
        with open(output_path, 'w', encoding='ascii') as f:
            f.write(config_content.strip())

        return output_path

    def _copy_set_file(self, set_file_path: str) -> str:
        """
        Copy .set file to MT5 presets folder.

        Args:
            set_file_path: Source .set file path

        Returns:
            Path to copied file in MT5 presets folder
        """
        # Ensure presets directory exists
        presets_dir = Path(self.config.presets_path)
        presets_dir.mkdir(parents=True, exist_ok=True)

        # Copy file
        filename = os.path.basename(set_file_path)
        dest_path = presets_dir / filename

        shutil.copy2(set_file_path, dest_path)
        return str(dest_path)

    def _find_latest_report(self, before_time: float) -> Optional[str]:
        """
        Find the most recent report file created after a given time.

        Args:
            before_time: Timestamp before test started

        Returns:
            Path to report file or None
        """
        # Search multiple locations where MT5 might save reports
        data_path = Path(self.config.data_path)
        report_patterns = [
            self.results_dir / "*.xml",
            self.results_dir / "*.htm",
            self.results_dir / "*.html",
            self.tester_dir / "*.xml",
            self.tester_dir / "*.htm",
            self.tester_dir / "*.html",
            data_path / "*.xml",
            data_path / "*.htm",
            data_path / "Reports" / "*.xml",
            data_path / "Reports" / "*.htm",
        ]

        latest_file = None
        latest_time = before_time

        for pattern in report_patterns:
            for filepath in pattern.parent.glob(pattern.name):
                file_time = os.path.getmtime(filepath)
                if file_time > latest_time:
                    latest_time = file_time
                    latest_file = str(filepath)

        return latest_file

    def _is_mt5_running(self) -> bool:
        """Check if MT5 terminal is currently running"""
        try:
            result = subprocess.run(
                ['tasklist', '/FI', 'IMAGENAME eq terminal64.exe'],
                capture_output=True,
                text=True
            )
            return 'terminal64.exe' in result.stdout
        except Exception:
            return False

    def _wait_for_completion(
        self,
        process: subprocess.Popen,
        timeout: int,
        start_time: float
    ) -> Optional[str]:
        """
        Wait for MT5 backtest to complete.

        Args:
            process: MT5 subprocess
            timeout: Maximum wait time in seconds
            start_time: Timestamp when test started

        Returns:
            Path to results file or None if timeout/error
        """
        elapsed = 0
        check_interval = 5  # seconds

        while elapsed < timeout:
            # Check if process exited
            if process.poll() is not None:
                print(f"MT5 exited with code: {process.returncode}")
                break

            # Check for results file
            report = self._find_latest_report(start_time)
            if report:
                # Wait a bit for file to be fully written
                time.sleep(2)
                return report

            time.sleep(check_interval)
            elapsed += check_interval
            print(f"Waiting for backtest... {elapsed}s / {timeout}s")

        # Timeout - try to find any report that was created
        report = self._find_latest_report(start_time)
        if report:
            return report

        # Kill process if still running
        if process.poll() is None:
            print("Timeout reached, terminating MT5...")
            process.terminate()
            process.wait(timeout=10)

        return None

    def run_backtest(
        self,
        set_file_path: str,
        backtest_config: Optional[BacktestConfig] = None,
        timeout: Optional[int] = None
    ) -> Dict[str, Any]:
        """
        Run a backtest with the given parameters.

        Args:
            set_file_path: Path to .set file with EA parameters
            backtest_config: Backtest settings. Uses defaults if not provided.
            timeout: Max wait time in seconds. Uses config default if not provided.

        Returns:
            Dictionary with:
                - success: bool
                - report_path: str or None
                - error: str or None
                - duration: float (seconds)
        """
        if backtest_config is None:
            config = get_config()
            backtest_config = config.backtest

        if timeout is None:
            timeout = backtest_config.timeout

        result = {
            "success": False,
            "report_path": None,
            "error": None,
            "duration": 0,
        }

        start_time = time.time()

        try:
            # Check if MT5 is already running
            if self._is_mt5_running():
                result["error"] = "MT5 is already running. Please close it first."
                return result

            # Copy .set file to presets
            preset_path = self._copy_set_file(set_file_path)
            print(f"Copied .set file to: {preset_path}")

            # Create config.ini
            config_path = self._create_config_ini(
                os.path.basename(preset_path),
                backtest_config
            )
            print(f"Created config: {config_path}")

            # Launch MT5 with config file
            terminal_exe = self.config.terminal_exe

            # Just use /config - MT5 should use its default data folder
            cmd = [
                terminal_exe,
                f"/config:{config_path}"
            ]

            print(f"Launching MT5: {terminal_exe}")
            print(f"  Config: {config_path}")

            process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
            )

            # Wait for completion
            report_path = self._wait_for_completion(process, timeout, start_time)

            if report_path:
                result["success"] = True
                result["report_path"] = report_path
                print(f"Backtest complete. Report: {report_path}")
            else:
                result["error"] = "No report file found after backtest"

        except FileNotFoundError as e:
            result["error"] = f"File not found: {e}"
        except Exception as e:
            result["error"] = f"Error running backtest: {e}"

        result["duration"] = time.time() - start_time
        return result

    def get_tester_cache_path(self) -> str:
        """Get path to tester cache folder"""
        return str(self.tester_dir / "cache")

    def clear_tester_cache(self) -> bool:
        """Clear the tester cache (useful for ensuring fresh tests)"""
        cache_path = Path(self.get_tester_cache_path())
        if cache_path.exists():
            try:
                shutil.rmtree(cache_path)
                return True
            except Exception as e:
                print(f"Error clearing cache: {e}")
                return False
        return True


class MT5ResultsWatcher:
    """
    Watches for new MT5 results files.
    Alternative approach using file system monitoring.
    """

    def __init__(self, watch_dir: str):
        self.watch_dir = Path(watch_dir)
        self.known_files = set()
        self._scan_existing()

    def _scan_existing(self):
        """Record existing files"""
        for ext in ['*.xml', '*.htm', '*.html']:
            for f in self.watch_dir.glob(ext):
                self.known_files.add(str(f))

    def get_new_files(self) -> list:
        """Get list of new files since last check"""
        new_files = []
        for ext in ['*.xml', '*.htm', '*.html']:
            for f in self.watch_dir.glob(ext):
                path = str(f)
                if path not in self.known_files:
                    new_files.append(path)
                    self.known_files.add(path)
        return new_files

    def wait_for_new_file(self, timeout: int = 600) -> Optional[str]:
        """Wait for a new results file to appear"""
        start = time.time()
        while time.time() - start < timeout:
            new_files = self.get_new_files()
            if new_files:
                # Return the most recent one
                return max(new_files, key=os.path.getmtime)
            time.sleep(2)
        return None


if __name__ == "__main__":
    # Test the controller
    from set_file_generator import SetFileGenerator

    print("Testing MT5 Controller...")

    try:
        controller = MT5Controller()
        print(f"MT5 Terminal: {controller.config.terminal_exe}")
        print(f"Tester Dir: {controller.tester_dir}")
        print(f"Results Dir: {controller.results_dir}")

        # Check if MT5 is running
        if controller._is_mt5_running():
            print("MT5 is currently running")
        else:
            print("MT5 is not running")

        print("\nController initialized successfully!")

    except Exception as e:
        print(f"Error: {e}")
